#!/usr/bin/env bash

main() {
  local command="${1:-run}"
  shift
  case "$command" in
  run)
    run "$@"
    ;;
  build-container)
    build_container "$@"
    ;;
  help)
    usage
    exit 0
    ;;
  *)
    usage
    exit 1
    ;;
  esac
}

usage() {
    cat <<EOF
$0 (run | build-container)
EOF
}

run() {
  if ! run_container; then
    build_container
    run_container
  fi
}

build_container() {
  docker build -t cr .
}

run_container() {
  docker run -it --rm -p 5000:5000 -v $(pwd):/source -v "$HOME"/.ssh:/home/cromo/.ssh cr
}

main "$@"
