#!/usr/bin/env bash

main() {
  local command="${1:-run}"
  shift
  case "$command" in
  run)
    run "$@"
    ;;
  build-container)
    build_container "$@"
    ;;
  deploy)
    deploy "$@"
    ;;
  shell)
    run bash
    ;;
  help)
    usage
    exit 0
    ;;
  *)
    usage
    exit 1
    ;;
  esac
}

usage() {
    cat <<EOF
$0 (run | build-container | deploy | shell)
EOF
}

run() {
  if ! run_container "$@"; then
    build_container
    run_container "$@"
  fi
}

deploy() {
  docker run -it --rm -v $(pwd):/source -v "$HOME"/.ssh:/home/cristian/.ssh cr bash -c 'lektor build && lektor deploy'
}

build_container() {
  docker build \
    --build-arg external_username=$(id --user --name) \
    --build-arg external_uid=$(id --user) \
    --build-arg external_gid=$(id --group) \
    -t cr .
}

run_container() {
  docker run -it --rm -p 5000:5000 -v $(pwd):/source -v "$HOME"/.ssh:/home/cristian/.ssh cr "$@"
}

main "$@"
